# Generated by Django 3.2.5 on 2021-09-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210916_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.URLField(default=0),
        ),
    ]
