# Generated by Django 3.2.5 on 2021-10-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
