# Generated by Django 3.2.5 on 2021-09-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_category_project_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='categoryId',
            new_name='category',
        ),
    ]
