# Generated by Django 3.2.5 on 2021-10-30 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0008_auto_20211030_1908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perk",
            name="minValue",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="perk",
            name="qtyLimit",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="anonymous",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="comment",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
