# Generated by Django 3.2.5 on 2021-11-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20211030_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://i.pinimg.com/originals/8f/05/17/8f0517135e33a3f1ad573d1dc16318b9.jpg'),
        ),
    ]
